name: MLflow Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 pandas scikit-learn numpy

    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local