name: CI/CD ML Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn docker

      - name: Set MLflow Tracking URI
        run: echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV

      - name: Run mlflow project
        run: |
          mlflow run ./MLProject --env-manager=local
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/rinimayasari2202/Workflow-CI.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

      - name: Build Docker Model from Latest DagsHub Run
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/rinimayasari2202/Workflow-CI.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          python -c "
          import mlflow
          runs = mlflow.search_runs(order_by=['start_time DESC'], max_results=1)
          if runs.empty:
              raise Exception('Tidak ditemukan run aktif di DagsHub!')
          latest_run_id = runs.iloc[0].run_id
          print(f'Berhasil mendapatkan Run ID terbaru: {latest_run_id}')
          
          import mlflow.models.python_api as mlflow_api
          mlflow_api.build_docker(
              model_uri=f'runs:/{latest_run_id}/model',
              image_name='my-model-image',
              env_manager='local'
          )
          "
          else:
              print('No runs found!')
          "

      - name: Build Docker Model
        run: |
          echo "Using Run ID: ${{ env.RUN_ID }}"
          mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/model" -n "my-model-image"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag my-model-image:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-model-image:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-model-image:latest